### ISSUE TITLE
adb.zip not found

### ISSUE THREAD

**Issue by cafelake** [AtlasTheProto/ADBForwarder#1]
Thanks for creating this!  I ran into the following issue.  Could it be that [this line](https://github.com/AtlasTheProto/ADBForwarder/blob/a1ae807b6f117d9283bcb2cd189ab8991896b045/Program.cs#L83) needs to use `Path.GetTempPath()` like the other lines?

```
C:\Users\me\Desktop>ADBForwarder
ADB not found, downloading in the background...
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\me\Desktop\adb.zip'.
File name: 'C:\Users\me\Desktop\adb.zip'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Ionic.Zip.ZipFile.get_ReadStream()
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at Ionic.Zip.ZipFile.Read(String fileName)
   at ADBForwarder.Program.DownloadADB()
   at ADBForwarder.Program.Main(String[] args)
```

**Comment by AtlasTheProto** [comment]
Total code refactor pushed, please try the new release and see if the issue persists.
